### ISSUE TITLE
Error when importing CSV

### ISSUE THREAD

**Issue by david-dd** [blutorange/baryllium#10]
![grafik](https://cloud.githubusercontent.com/assets/19301693/24189035/cbc83254-0ee3-11e7-8bdf-f0aaa076af1b.png)

**Comment by blutorange** [comment]
http://stackoverflow.com/a/20231349

Do a `doctrine orm:generate-proxies` instead of just an update from the doctrine menu.

@david-dd Please confirm whether this works

**Comment by blutorange** [comment]
Also, when you set the `default_database` in `phinx.yml` to `development`, the proxies should be regenerated and you should not get this error.
