### ISSUE TITLE
Login when not authorized

### ISSUE THREAD

**Issue by CaptainMalzbier** [blutorange/baryllium#11]
When trying to access a page requiring authorization, show some login screen to the user and let him login. And redirect him to the page he tried to access.

**Comment by blutorange** [comment]
Users are now redirected to the login screen when authorization is required (and back to the original page afterwards, of course). Uses the custom URL param `redirecturl`. Please test and report back.

**Comment by blutorange** [comment]
Reopen when there are any issues.
